version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: campusecorival
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - app-network

  web:
    image: nginx:latest
    container_name: web
    ports:
      - "8080:80"
    depends_on:
      - server
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./WebHookSite.js:/usr/share/nginx/html/WebHookSite.js
      - ./WebHookSite.css:/usr/share/nginx/html/WebHookSite.css
      - ./images:/usr/share/nginx/html/images
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
